import { app, BrowserWindow, dialog } from 'electron';
import { ClaudeManager } from '../utils/claudeManager';
import { SessionStore } from '../utils/sessionStore';
import { setupIpcHandlers } from '../ipc/handlers';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow;
const claudeManager = new ClaudeManager();
const sessionStore = new SessionStore();
let claudeStatus = { connected: false, version: 'unknown', path: 'unknown' };

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    title: 'Commander',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false
    },
  });

  // Window loading is now done after IPC handlers are set up
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  // Initialize Claude binary
  try {
    const info = await claudeManager.initialize();
    claudeStatus = { connected: true, version: info.version, path: info.path };
    console.log('Claude initialized:', info);
  } catch (error) {
    console.error('Failed to initialize Claude:', error);
    claudeStatus = { connected: false, version: 'unknown', path: 'unknown' };
    dialog.showErrorBox('Claude Code Not Found', (error as Error).message);
    app.quit();
    return;
  }

  createWindow();
  
  // Set up IPC handlers BEFORE loading the window content
  setupIpcHandlers(mainWindow, claudeManager, sessionStore, claudeStatus);
  
  // Load the window content AFTER handlers are set up
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
  // Open the DevTools in development
  if (process.env.NODE_ENV !== 'production') {
    mainWindow.webContents.openDevTools();
  }
});

// Quit when all windows are closed on all platforms
app.on('window-all-closed', () => {
  app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
